# Generated by Django 5.0.1 on 2024-01-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='Product',
        ),
    ]
